# Generated by Django 5.2.7 on 2026-09-15 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_contactmessage_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_file',
            field=models.ImageField(blank=True, help_text='Upload brand logo file', null=True, upload_to='brands/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload category image file', null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(blank=True, help_text='Upload primary product photo directly from your device', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.CharField(blank=True, help_text='External logo URL (optional fallback)', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, help_text='External image URL (optional fallback)', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='images_json',
            field=models.TextField(default='[]', help_text='JSON array of image URLs or paths, e.g. ["/static/images/hero.jpg"]'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload extra gallery photo', upload_to='products/gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='store.product')),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'verbose_name_plural': 'Gallery Photos',
                'ordering': ['order', 'id'],
            },
        ),
    ]
