# Generated by Django 5.2.17 on 2026-09-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_brand_logo_file_category_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fatoorah_invoice_id',
            field=models.CharField(blank=True, help_text='MyFatoorah Invoice ID', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='fatoorah_payment_id',
            field=models.CharField(blank=True, help_text='MyFatoorah Payment ID', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='fatoorah_transaction_id',
            field=models.CharField(blank=True, help_text='Bank transaction reference', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_response_json',
            field=models.TextField(blank=True, default='{}', help_text='Raw verification payload'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('cancelled', 'Cancelled'), ('cod', 'Cash on Delivery')], default='pending', max_length=20),
        ),
    ]
