# Generated by Django 5.2.7 on 2026-09-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_brand_logo_file_category_image_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal banner title / heading', max_length=200)),
                ('title_ar', models.CharField(blank=True, help_text='Arabic title (optional)', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Banner subtitle / description (optional)')),
                ('subtitle_ar', models.TextField(blank=True, help_text='Arabic subtitle (optional)')),
                ('image', models.ImageField(blank=True, help_text='Upload the banner image directly from your device', null=True, upload_to='banners/')),
                ('image_url', models.CharField(blank=True, help_text='Or provide an external/static image path (e.g. /images/hero-station.jpg)', max_length=500)),
                ('banner_type', models.CharField(choices=[('hero', 'Store Homepage Hero Banner'), ('promo', 'Store Promotional / Offer Banner'), ('admin', 'Admin Panel Executive Banner')], default='hero', help_text='Location where this banner is displayed', max_length=20)),
                ('link_url', models.CharField(blank=True, help_text='Destination link URL when banner or button is clicked (e.g. /en/shop/)', max_length=255)),
                ('button_text', models.CharField(blank=True, help_text='Button label text (optional)', max_length=80)),
                ('button_text_ar', models.CharField(blank=True, help_text='Arabic button label text (optional)', max_length=80)),
                ('is_active', models.BooleanField(default=True, help_text='Check to activate this banner on the site')),
                ('order', models.IntegerField(default=0, help_text='Display ordering priority (lowest number first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner & Promotion',
                'verbose_name_plural': 'Banners & Promotions',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
