# Generated by Django 5.2.17 on 2026-09-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_fatoorah_invoice_id_order_fatoorah_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fatoorah_gateway_link',
            field=models.TextField(blank=True, help_text='Direct hosted invoice payment link'),
        ),
    ]
