# Generated by Django 5.2.17 on 2026-09-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_banner'),
        ('store', '0005_order_fatoorah_gateway_link'),
    ]

    operations = [
    ]
